03 mongodb
pabearyoga/nodejs-homework-rest-api pull request #2
Opened 2022-12-08 21:57 UTC by pabearyoga

hw03. REST API. MongoDB and Mongoose.

2022-12-09 12:33 UTC, BohdanGres requested changes
все добре, декілька косметичних зауважень, але загалом молодець

2022-12-09 12:33 UTC, BohdanGres commented on controllers/contacts/addContact.js
> +    const { error } = addSchema.validate(req.body);
винеси цю валідацію в мідлварку

2022-12-09 12:33 UTC, BohdanGres commented on controllers/contacts/updateStatusContact.js
> +
оці всі перевірки теж винеси, тоді контродер буде охайнішим

2022-12-09 20:46 UTC, pabearyoga commented
все пофіксив)

2022-12-10 08:26 UTC, BohdanGres approved these changes

2022-12-10 08:33 UTC, merged