04 auth
pabearyoga/nodejs-homework-rest-api pull request #3
Opened 2022-12-16 19:05 UTC by pabearyoga

ДЗ Модуль №4 "Аутентефікація"

2022-12-17 09:41 UTC, BohdanGres requested changes
все добре, в тебе багато дуже схожих мідлварок, подумай як можна зробити менше кода

2022-12-17 09:41 UTC, BohdanGres commented on app.js
>  app.use("/api/contacts", contactsRouter);
можеш сюди одразу навісити мідлварку для авторізації, бо вона на всі ці роути потрібна

2022-12-17 09:41 UTC, BohdanGres commented on middlewares/users/auth.js
> +    if (!user || user.token === null) {
забув перевірити чи user.token === token

2022-12-18 15:05 UTC, pabearyoga commented on app.js
>  app.use("/api/contacts", contactsRouter);
для login i logou мідлварка для авторізації не потрібна ніби ?!

2022-12-18 15:12 UTC, pabearyoga commented on middlewares/users/auth.js
> +    if (!user || user.token === null) {
fix

2022-12-21 07:39 UTC, BohdanGres approved these changes

2022-12-21 21:38 UTC, merged